server.port: 8082

spring.profiles.active: local

---

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092, localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-consumer-group

  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: none
    # hibernate.ddl-auto: create-drop
  datasource:
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    # persistent store
    # url: jdbc:h2:file:~/data/dump
    # volatile store
    url: jdbc:h2:mem:kafka-poc

kafka.topic-id: library-events