server.port: 8081

spring.profiles.active: local

---

spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library-events

    producer:
      bootstrap-servers: localhost:29092, localhost:39092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 2000

    admin:
      properties:
        bootstrap.servers: localhost:29092, localhost:39092

---

spring:
  config:
    activate:
      on-profile: uat
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:99095,localhost:99096,localhost:99097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:<location>/client.truststore.jks
        trust-store-password: password
        key-store-location: file:<location>/client.keystore.jks
        key-store-password: password
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm: