server.port: 8081

spring.profiles.active: local

---

spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:9090, localhost:9091
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9090, localhost:9091